// <auto-generated />
using System;
using HobbyXP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HobbyXP.Data.Migrations
{
    [DbContext(typeof(HobbyXpDbContext))]
    [Migration("20260821150110_AddRewardPurchaseDetails")]
    partial class AddRewardPurchaseDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("HobbyXP.Models.Achievements.AchievementRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FlatBonusPoints")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PointsPerUnit")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitLabel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActionType")
                        .IsUnique();

                    b.ToTable("AchievementRules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionType = "RunningKilometer",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Running por kilómetro",
                            IsActive = true,
                            PointsPerUnit = 10m,
                            UnitLabel = "km"
                        },
                        new
                        {
                            Id = 2,
                            ActionType = "GymWorkoutSaved",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Sesión de gimnasio",
                            IsActive = true,
                            PointsPerUnit = 25m,
                            UnitLabel = "sesión"
                        },
                        new
                        {
                            Id = 3,
                            ActionType = "ProgressiveOverload",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Sobrecarga progresiva",
                            FlatBonusPoints = 150,
                            IsActive = true,
                            PointsPerUnit = 0m,
                            UnitLabel = "logro"
                        },
                        new
                        {
                            Id = 4,
                            ActionType = "OfficialRaceCompleted",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Carrera oficial completada",
                            FlatBonusPoints = 500,
                            IsActive = true,
                            PointsPerUnit = 0m,
                            UnitLabel = "carrera"
                        },
                        new
                        {
                            Id = 5,
                            ActionType = "PuzzleCompleted",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Rompecabezas completado",
                            IsActive = true,
                            PointsPerUnit = 50m,
                            UnitLabel = "rompecabezas"
                        },
                        new
                        {
                            Id = 6,
                            ActionType = "MediaCompleted",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Serie o película terminada",
                            IsActive = true,
                            PointsPerUnit = 30m,
                            UnitLabel = "obra"
                        },
                        new
                        {
                            Id = 7,
                            ActionType = "VideoGamePercent",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Avance de videojuego",
                            IsActive = true,
                            PointsPerUnit = 10m,
                            UnitLabel = "%"
                        },
                        new
                        {
                            Id = 8,
                            ActionType = "VideoGamePlatinum",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Videojuego platinado",
                            FlatBonusPoints = 1000,
                            IsActive = true,
                            PointsPerUnit = 0m,
                            UnitLabel = "juego"
                        },
                        new
                        {
                            Id = 9,
                            ActionType = "BookPageRead",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Página leída",
                            IsActive = true,
                            PointsPerUnit = 1m,
                            UnitLabel = "página"
                        },
                        new
                        {
                            Id = 10,
                            ActionType = "BookCompleted",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Libro terminado",
                            FlatBonusPoints = 200,
                            IsActive = true,
                            PointsPerUnit = 0m,
                            UnitLabel = "libro"
                        },
                        new
                        {
                            Id = 11,
                            ActionType = "CourseCompleted",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Curso terminado",
                            FlatBonusPoints = 100,
                            IsActive = true,
                            PointsPerUnit = 0m,
                            UnitLabel = "curso"
                        },
                        new
                        {
                            Id = 12,
                            ActionType = "CourseSessionCompleted",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Sesión de curso",
                            IsActive = true,
                            PointsPerUnit = 10m,
                            UnitLabel = "sesión"
                        },
                        new
                        {
                            Id = 13,
                            ActionType = "MediaChapterWatched",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Capítulo de serie",
                            IsActive = true,
                            PointsPerUnit = 5m,
                            UnitLabel = "capítulo"
                        },
                        new
                        {
                            Id = 14,
                            ActionType = "DietMealOnPlan",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Comida en plan",
                            IsActive = true,
                            PointsPerUnit = 15m,
                            UnitLabel = "comida"
                        },
                        new
                        {
                            Id = 15,
                            ActionType = "DietPerfectDay",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Día perfecto de dieta",
                            FlatBonusPoints = 40,
                            IsActive = true,
                            PointsPerUnit = 0m,
                            UnitLabel = "día"
                        });
                });

            modelBuilder.Entity("HobbyXP.Models.Achievements.EarnedMedal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MedalDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceEntityType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MedalDefinitionId", "EarnedAt");

                    b.ToTable("EarnedMedals", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Achievements.MedalDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("IconPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnlockHint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("MedalDefinitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "GoldRace",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Completaste tu primera carrera oficial.",
                            IconPath = "Assets/Medals/official-race.png",
                            Name = "Medalla de Oro",
                            UnlockHint = "Marca una carrera oficial como completada."
                        },
                        new
                        {
                            Id = 2,
                            Code = "PlatinumGame",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Platinaste tu primer videojuego al 100%.",
                            IconPath = "Assets/Medals/platinum-game.png",
                            Name = "Medalla de Platino",
                            UnlockHint = "Lleva un videojuego al 100% de completitud."
                        },
                        new
                        {
                            Id = 3,
                            Code = "ProgressiveOverload",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Superaste tu récord histórico en gimnasio.",
                            IconPath = "Assets/Medals/progressive-overload.png",
                            Name = "Sobrecarga Progresiva",
                            UnlockHint = "Mejora peso o tiempo respecto a tu máximo anterior."
                        },
                        new
                        {
                            Id = 4,
                            Code = "BookCompleted",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Terminaste tu primer libro de principio a fin.",
                            IconPath = "Assets/Medals/book-completed.png",
                            Name = "Lector Voraz",
                            UnlockHint = "Marca un libro como completado."
                        },
                        new
                        {
                            Id = 5,
                            Code = "CourseCompleted",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Completaste tu primer curso.",
                            IconPath = "Assets/Medals/course-completed.png",
                            Name = "Graduado",
                            UnlockHint = "Finaliza un curso registrando todas sus sesiones."
                        },
                        new
                        {
                            Id = 6,
                            Code = "PuzzleMaster",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Completaste tu primer rompecabezas.",
                            IconPath = "Assets/Medals/puzzle.png",
                            Name = "Maestro del Puzzle",
                            UnlockHint = "Registra un rompecabezas como terminado."
                        },
                        new
                        {
                            Id = 7,
                            Code = "MediaMarathon",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Terminaste tu primera serie o película.",
                            IconPath = "Assets/Medals/media.png",
                            Name = "Maratón Cultural",
                            UnlockHint = "Registra una obra de entretenimiento como completada."
                        },
                        new
                        {
                            Id = 8,
                            Code = "RacesCompleted3",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tres carreras oficiales en tu historial.",
                            IconPath = "Assets/Medals/official-race.png",
                            Name = "Podio en Entrenamiento",
                            UnlockHint = "Completa 3 carreras oficiales."
                        },
                        new
                        {
                            Id = 9,
                            Code = "RacesCompleted5",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cinco carreras oficiales conquistadas.",
                            IconPath = "Assets/Medals/official-race.png",
                            Name = "Corredor Constante",
                            UnlockHint = "Completa 5 carreras oficiales."
                        },
                        new
                        {
                            Id = 10,
                            Code = "RacesCompleted10",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Diez carreras oficiales en tu palmarés.",
                            IconPath = "Assets/Medals/official-race.png",
                            Name = "Veterano del Asfalto",
                            UnlockHint = "Completa 10 carreras oficiales."
                        },
                        new
                        {
                            Id = 11,
                            Code = "RacesCompleted25",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Veinticinco carreras oficiales. Eres imparable.",
                            IconPath = "Assets/Medals/official-race.png",
                            Name = "Leyenda del Chip",
                            UnlockHint = "Completa 25 carreras oficiales."
                        },
                        new
                        {
                            Id = 12,
                            Code = "RunningSessions10",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Diez sesiones de running registradas.",
                            IconPath = "Assets/Medals/running-session.png",
                            Name = "Ritmo de Reloj",
                            UnlockHint = "Registra 10 sesiones de running."
                        },
                        new
                        {
                            Id = 13,
                            Code = "RunningSessions50",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cincuenta salidas al asfalto.",
                            IconPath = "Assets/Medals/running-session.png",
                            Name = "Motor Cardíaco",
                            UnlockHint = "Registra 50 sesiones de running."
                        },
                        new
                        {
                            Id = 14,
                            Code = "RunningSessions100",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cien sesiones. El GPS te conoce por nombre.",
                            IconPath = "Assets/Medals/running-session.png",
                            Name = "Máquina de Correr",
                            UnlockHint = "Registra 100 sesiones de running."
                        },
                        new
                        {
                            Id = 15,
                            Code = "RunningKm100",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Acumulaste 100 km corriendo.",
                            IconPath = "Assets/Medals/running-km.png",
                            Name = "Centurión del Kilómetro",
                            UnlockHint = "Corre un total de 100 km."
                        },
                        new
                        {
                            Id = 16,
                            Code = "RunningKm500",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "500 km en tus piernas.",
                            IconPath = "Assets/Medals/running-km.png",
                            Name = "Conquistador del Asfalto",
                            UnlockHint = "Corre un total de 500 km."
                        },
                        new
                        {
                            Id = 17,
                            Code = "RunningKm1000",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "1.000 km. Distancia de leyenda.",
                            IconPath = "Assets/Medals/running-km.png",
                            Name = "Ultra Alma",
                            UnlockHint = "Corre un total de 1.000 km."
                        },
                        new
                        {
                            Id = 18,
                            Code = "ProgressiveOverload5",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cinco récords personales en el gym.",
                            IconPath = "Assets/Medals/progressive-overload.png",
                            Name = "Forja de Hierro",
                            UnlockHint = "Logra 5 sobrecargas progresivas."
                        },
                        new
                        {
                            Id = 19,
                            Code = "ProgressiveOverload10",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Diez PRs. Cada sesión te hace más fuerte.",
                            IconPath = "Assets/Medals/progressive-overload.png",
                            Name = "Titán en Evolución",
                            UnlockHint = "Logra 10 sobrecargas progresivas."
                        },
                        new
                        {
                            Id = 20,
                            Code = "ProgressiveOverload25",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Veinticinco récords rotos. El gym tiembla.",
                            IconPath = "Assets/Medals/progressive-overload.png",
                            Name = "Coloso del Hierro",
                            UnlockHint = "Logra 25 sobrecargas progresivas."
                        },
                        new
                        {
                            Id = 21,
                            Code = "GymWorkouts10",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Diez entrenamientos guardados.",
                            IconPath = "Assets/Medals/gym-workout.png",
                            Name = "Hierro Temprano",
                            UnlockHint = "Registra 10 sesiones de gimnasio."
                        },
                        new
                        {
                            Id = 22,
                            Code = "GymWorkouts50",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cincuenta sesiones de gimnasio.",
                            IconPath = "Assets/Medals/gym-workout.png",
                            Name = "Forja Personal",
                            UnlockHint = "Registra 50 sesiones de gimnasio."
                        },
                        new
                        {
                            Id = 23,
                            Code = "GymWorkouts100",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cien entrenamientos. Disciplina pura.",
                            IconPath = "Assets/Medals/gym-workout.png",
                            Name = "Titán del Gym",
                            UnlockHint = "Registra 100 sesiones de gimnasio."
                        },
                        new
                        {
                            Id = 24,
                            Code = "GymWorkouts250",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Doscientos cincuenta sesiones. Eres una institución.",
                            IconPath = "Assets/Medals/gym-workout.png",
                            Name = "Monolito Humano",
                            UnlockHint = "Registra 250 sesiones de gimnasio."
                        },
                        new
                        {
                            Id = 25,
                            Code = "PlatinumGames3",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tres juegos al 100%.",
                            IconPath = "Assets/Medals/platinum-game.png",
                            Name = "Coleccionista Platino",
                            UnlockHint = "Platina 3 videojuegos."
                        },
                        new
                        {
                            Id = 26,
                            Code = "PlatinumGames5",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cinco platinos en la estantería virtual.",
                            IconPath = "Assets/Medals/platinum-game.png",
                            Name = "Salón Digital",
                            UnlockHint = "Platina 5 videojuegos."
                        },
                        new
                        {
                            Id = 27,
                            Code = "PlatinumGames10",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Diez juegos al 100%. Completionista nato.",
                            IconPath = "Assets/Medals/platinum-game.png",
                            Name = "Meta Absoluta",
                            UnlockHint = "Platina 10 videojuegos."
                        },
                        new
                        {
                            Id = 28,
                            Code = "BooksCompleted5",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cinco libros terminados.",
                            IconPath = "Assets/Medals/book-completed.png",
                            Name = "Club del Capítulo Cinco",
                            UnlockHint = "Completa 5 libros."
                        },
                        new
                        {
                            Id = 29,
                            Code = "BooksCompleted10",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Diez libros en tu historial.",
                            IconPath = "Assets/Medals/book-completed.png",
                            Name = "Bibliófilo de Garra",
                            UnlockHint = "Completa 10 libros."
                        },
                        new
                        {
                            Id = 30,
                            Code = "BooksCompleted25",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Veinticinco libros conquistados.",
                            IconPath = "Assets/Medals/book-completed.png",
                            Name = "Estantería Legendaria",
                            UnlockHint = "Completa 25 libros."
                        },
                        new
                        {
                            Id = 31,
                            Code = "BooksCompleted50",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cincuenta libros. Tu mente es un faro.",
                            IconPath = "Assets/Medals/book-completed.png",
                            Name = "Faros del Conocimiento",
                            UnlockHint = "Completa 50 libros."
                        },
                        new
                        {
                            Id = 32,
                            Code = "BooksCompleted100",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cien libros. Biblioteca personal de élite.",
                            IconPath = "Assets/Medals/book-completed.png",
                            Name = "Archivo del Sabio",
                            UnlockHint = "Completa 100 libros."
                        },
                        new
                        {
                            Id = 33,
                            Code = "BookPages1000",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Leíste 1.000 páginas en total.",
                            IconPath = "Assets/Medals/book-pages.png",
                            Name = "Mil Páginas de Gloria",
                            UnlockHint = "Acumula 1.000 páginas leídas."
                        },
                        new
                        {
                            Id = 34,
                            Code = "BookPages5000",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "5.000 páginas devoradas.",
                            IconPath = "Assets/Medals/book-pages.png",
                            Name = "Crónica Infinita",
                            UnlockHint = "Acumula 5.000 páginas leídas."
                        },
                        new
                        {
                            Id = 35,
                            Code = "BookPages10000",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "10.000 páginas. Llevas una biblioteca encima.",
                            IconPath = "Assets/Medals/book-pages.png",
                            Name = "Biblioteca Ambulante",
                            UnlockHint = "Acumula 10.000 páginas leídas."
                        },
                        new
                        {
                            Id = 36,
                            Code = "CoursesCompleted3",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tres cursos terminados.",
                            IconPath = "Assets/Medals/course-completed.png",
                            Name = "Trilogía Académica",
                            UnlockHint = "Completa 3 cursos."
                        },
                        new
                        {
                            Id = 37,
                            Code = "CoursesCompleted5",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cinco cursos en tu currículo.",
                            IconPath = "Assets/Medals/course-completed.png",
                            Name = "Aprobado con Honores",
                            UnlockHint = "Completa 5 cursos."
                        },
                        new
                        {
                            Id = 38,
                            Code = "CoursesCompleted10",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Diez cursos. Aprendiz perpetuo.",
                            IconPath = "Assets/Medals/course-completed.png",
                            Name = "Multidisciplinar",
                            UnlockHint = "Completa 10 cursos."
                        },
                        new
                        {
                            Id = 39,
                            Code = "CoursesCompleted25",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Veinticinco cursos. Academia propia.",
                            IconPath = "Assets/Medals/course-completed.png",
                            Name = "Erudito Empírico",
                            UnlockHint = "Completa 25 cursos."
                        },
                        new
                        {
                            Id = 40,
                            Code = "CourseSessions25",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Veinticinco sesiones de curso registradas.",
                            IconPath = "Assets/Medals/course-sessions.png",
                            Name = "Asistencia Ejemplar",
                            UnlockHint = "Registra 25 sesiones de curso."
                        },
                        new
                        {
                            Id = 41,
                            Code = "CourseSessions50",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cincuenta sesiones de estudio.",
                            IconPath = "Assets/Medals/course-sessions.png",
                            Name = "Beca de Disciplina",
                            UnlockHint = "Registra 50 sesiones de curso."
                        },
                        new
                        {
                            Id = 42,
                            Code = "CourseSessions100",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cien sesiones. El conocimiento te persigue.",
                            IconPath = "Assets/Medals/course-sessions.png",
                            Name = "Doctor Honoris Causa",
                            UnlockHint = "Registra 100 sesiones de curso."
                        },
                        new
                        {
                            Id = 43,
                            Code = "PuzzlesCompleted5",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cinco rompecabezas resueltos.",
                            IconPath = "Assets/Medals/puzzle.png",
                            Name = "Pieza a Pieza",
                            UnlockHint = "Completa 5 rompecabezas."
                        },
                        new
                        {
                            Id = 44,
                            Code = "PuzzlesCompleted10",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Diez puzzles. Orden desde el caos.",
                            IconPath = "Assets/Medals/puzzle.png",
                            Name = "Arquitecto del Caos",
                            UnlockHint = "Completa 10 rompecabezas."
                        },
                        new
                        {
                            Id = 45,
                            Code = "PuzzlesCompleted25",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Veinticinco rompecabezas dominados.",
                            IconPath = "Assets/Medals/puzzle.png",
                            Name = "Visión Escher",
                            UnlockHint = "Completa 25 rompecabezas."
                        },
                        new
                        {
                            Id = 46,
                            Code = "PuzzlesCompleted50",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cincuenta puzzles. Ninguna pieza te resiste.",
                            IconPath = "Assets/Medals/puzzle.png",
                            Name = "Maestro del Encaje",
                            UnlockHint = "Completa 50 rompecabezas."
                        },
                        new
                        {
                            Id = 47,
                            Code = "PuzzlesCompleted100",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cien rompecabezas. Tu mesa es un templo.",
                            IconPath = "Assets/Medals/puzzle.png",
                            Name = "Leyenda del Tablero",
                            UnlockHint = "Completa 100 rompecabezas."
                        },
                        new
                        {
                            Id = 48,
                            Code = "MediaCompleted5",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cinco obras terminadas.",
                            IconPath = "Assets/Medals/media.png",
                            Name = "Noche de Palomitas",
                            UnlockHint = "Completa 5 series o películas."
                        },
                        new
                        {
                            Id = 49,
                            Code = "MediaCompleted10",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Diez maratones en el sofá.",
                            IconPath = "Assets/Medals/media.png",
                            Name = "Binge Profesional",
                            UnlockHint = "Completa 10 series o películas."
                        },
                        new
                        {
                            Id = 50,
                            Code = "MediaCompleted25",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Veinticinco obras en tu historial.",
                            IconPath = "Assets/Medals/media.png",
                            Name = "Cinéfilo Serial",
                            UnlockHint = "Completa 25 series o películas."
                        },
                        new
                        {
                            Id = 51,
                            Code = "MediaCompleted50",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cincuenta obras. El control remoto es tuyo.",
                            IconPath = "Assets/Medals/media.png",
                            Name = "Sofá Olímpico",
                            UnlockHint = "Completa 50 series o películas."
                        },
                        new
                        {
                            Id = 52,
                            Code = "MediaCompleted100",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cien obras. Algoritmo personalizado.",
                            IconPath = "Assets/Medals/media.png",
                            Name = "Palmarés del Streaming",
                            UnlockHint = "Completa 100 series o películas."
                        },
                        new
                        {
                            Id = 53,
                            Code = "DietGoodDays1",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Completaste tu primer día bueno de dieta (3 de 4 comidas en plan).",
                            IconPath = "Assets/Medals/gym-workout.png",
                            Name = "Primer Plato",
                            UnlockHint = "Registra un día con al menos 3 comidas en plan."
                        },
                        new
                        {
                            Id = 54,
                            Code = "DietGoodDays10",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Diez días buenos de dieta.",
                            IconPath = "Assets/Medals/gym-workout.png",
                            Name = "Disciplina en la Mesa",
                            UnlockHint = "Acumula 10 días con al menos 3 comidas en plan."
                        },
                        new
                        {
                            Id = 55,
                            Code = "DietGoodDays50",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cincuenta días buenos. El plan ya es costumbre.",
                            IconPath = "Assets/Medals/gym-workout.png",
                            Name = "Hábito Forjado",
                            UnlockHint = "Acumula 50 días con al menos 3 comidas en plan."
                        },
                        new
                        {
                            Id = 56,
                            Code = "DietPerfectDays7",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Siete días perfectos (4/4 en plan).",
                            IconPath = "Assets/Medals/progressive-overload.png",
                            Name = "Semana Impecable",
                            UnlockHint = "Acumula 7 días con las 4 comidas en plan."
                        },
                        new
                        {
                            Id = 57,
                            Code = "DietPerfectDays30",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Treinta días perfectos. Adherencia de élite.",
                            IconPath = "Assets/Medals/progressive-overload.png",
                            Name = "Mes de Acero",
                            UnlockHint = "Acumula 30 días con las 4 comidas en plan."
                        });
                });

            modelBuilder.Entity("HobbyXP.Models.Achievements.Reward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CostInPoints")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("PurchaseUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RedeemedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RedeemedCostInPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceType");

                    b.HasIndex("Status");

                    b.ToTable("Rewards", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Core.DailyQuotaEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActualPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DayUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("GlobalXpRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HobbyLevelAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HobbyLevelBefore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HobbyXpRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PenalizedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequiredPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RestoredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceType", "DayUtc")
                        .IsUnique();

                    b.ToTable("DailyQuotaEvaluations", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Core.HobbyProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<int>("PlayerProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("SpendableXp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalXp")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerProfileId", "SourceType")
                        .IsUnique();

                    b.ToTable("HobbyProgresses", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Core.Milestone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAt");

                    b.ToTable("Milestones", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Core.PlayerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("BaseXpPerLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1000);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("DailyQuotaTrackingStartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DisciplineImmunityUntilUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Aventurero");

                    b.Property<int?>("EquippedRewardId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HobbySpendableLedgerInitialized")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("HonorTitle")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("LastSeenEarnedMedalCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<bool>("SpendableLedgerInitialized")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("SpendableProgressBaselineApplied")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("SpendableXp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalXp")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WeeklyQuotaTrackingStartedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PlayerProfiles", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Core.WeeklyQuotaEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActualPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActualSecondary")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GlobalXpRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HobbyLevelAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HobbyLevelBefore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HobbyXpRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PenalizedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequiredPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequiredSecondary")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RestoredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WeekStartUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceType", "WeekStartUtc")
                        .IsUnique();

                    b.ToTable("WeeklyQuotaEvaluations", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Core.XpTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGlobal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("PlayerProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceEntityType")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EarnedAt");

                    b.HasIndex("PlayerProfileId");

                    b.HasIndex("SourceType");

                    b.ToTable("XpTransactions", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Entertainment.MediaEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("XpEarned")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAt");

                    b.ToTable("MediaEntries", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Entertainment.MediaSeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChaptersWatched")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CompletedMediaEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalChapters")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("XpEarned")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("MediaSeries", null, t =>
                        {
                            t.HasCheckConstraint("CK_MediaSeries_ChaptersWatched", "[ChaptersWatched] >= 0 AND [ChaptersWatched] <= [TotalChapters]");
                        });
                });

            modelBuilder.Entity("HobbyXP.Models.Entertainment.MediaSeriesChapterLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChaptersDone")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WatchDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaSeriesId", "WatchDate");

                    b.ToTable("MediaSeriesChapterLogs", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Entertainment.Puzzle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PieceCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("XpEarned")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Puzzles", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Entertainment.VideoGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletionPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlatinumBonusXp")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PlatinumUnlockedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("XpEarned")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompletionPercentage");

                    b.HasIndex("Status");

                    b.ToTable("VideoGames", null, t =>
                        {
                            t.HasCheckConstraint("CK_VideoGames_CompletionPercentage", "[CompletionPercentage] >= 0 AND [CompletionPercentage] <= 100");
                        });
                });

            modelBuilder.Entity("HobbyXP.Models.Entertainment.VideoGameProgressLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PercentDelta")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ProgressDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("VideoGameId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VideoGameId", "ProgressDate");

                    b.ToTable("VideoGameProgressLogs", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Feedback.Suggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Kind");

                    b.HasIndex("ReportedAt");

                    b.HasIndex("Status");

                    b.ToTable("Suggestions", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.PersonalGrowth.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PagesRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalPages")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("XpEarned")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("Books", null, t =>
                        {
                            t.HasCheckConstraint("CK_Books_PagesRead", "[PagesRead] >= 0 AND [PagesRead] <= [TotalPages]");
                        });
                });

            modelBuilder.Entity("HobbyXP.Models.PersonalGrowth.BookReadingLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PagesDone")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReadDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookId", "ReadDate");

                    b.ToTable("BookReadingLogs", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.PersonalGrowth.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalSessions")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("XpEarned")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("Courses", null, t =>
                        {
                            t.HasCheckConstraint("CK_Courses_SessionsCompleted", "[SessionsCompleted] >= 0 AND [SessionsCompleted] <= [TotalSessions]");
                        });
                });

            modelBuilder.Entity("HobbyXP.Models.PersonalGrowth.CourseSessionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionsDone")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "SessionDate");

                    b.ToTable("CourseSessionLogs", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Physical.DietDayLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BreakfastStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DayDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DinnerStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("LunchStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("OnPlanCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SnackStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("XpEarned")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DayDate")
                        .IsUnique();

                    b.ToTable("DietDayLogs", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Physical.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("MuscleGroup")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MuscleGroup");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Exercises", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Physical.GymWorkout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TriggeredProgressiveOverload")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WorkoutDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("XpEarned")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutDate");

                    b.ToTable("GymWorkouts", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Physical.GymWorkoutEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("GymWorkoutId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPersonalRecord")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Repetitions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sets")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(8, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GymWorkoutId");

                    b.HasIndex("ExerciseId", "CreatedAt");

                    b.ToTable("GymWorkoutEntries", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Physical.OfficialRace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BonusXpAwarded")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DistanceKm")
                        .HasPrecision(8, 3)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsCompleted");

                    b.ToTable("OfficialRaces", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Physical.RunningSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CarreraId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DistanceKm")
                        .HasPrecision(8, 3)
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double>("PaceMinPerKm")
                        .HasPrecision(8, 3)
                        .HasColumnType("REAL");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("XpEarned")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.HasIndex("RecordedAt");

                    b.HasIndex("SessionType");

                    b.ToTable("RunningSessions", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Achievements.EarnedMedal", b =>
                {
                    b.HasOne("HobbyXP.Models.Achievements.MedalDefinition", "MedalDefinition")
                        .WithMany("EarnedInstances")
                        .HasForeignKey("MedalDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MedalDefinition");
                });

            modelBuilder.Entity("HobbyXP.Models.Core.HobbyProgress", b =>
                {
                    b.HasOne("HobbyXP.Models.Core.PlayerProfile", "PlayerProfile")
                        .WithMany("HobbyProgresses")
                        .HasForeignKey("PlayerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerProfile");
                });

            modelBuilder.Entity("HobbyXP.Models.Core.XpTransaction", b =>
                {
                    b.HasOne("HobbyXP.Models.Core.PlayerProfile", "PlayerProfile")
                        .WithMany("Transactions")
                        .HasForeignKey("PlayerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerProfile");
                });

            modelBuilder.Entity("HobbyXP.Models.Entertainment.MediaSeriesChapterLog", b =>
                {
                    b.HasOne("HobbyXP.Models.Entertainment.MediaSeries", "MediaSeries")
                        .WithMany("ChapterLogs")
                        .HasForeignKey("MediaSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaSeries");
                });

            modelBuilder.Entity("HobbyXP.Models.Entertainment.VideoGameProgressLog", b =>
                {
                    b.HasOne("HobbyXP.Models.Entertainment.VideoGame", "VideoGame")
                        .WithMany("ProgressLogs")
                        .HasForeignKey("VideoGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VideoGame");
                });

            modelBuilder.Entity("HobbyXP.Models.PersonalGrowth.BookReadingLog", b =>
                {
                    b.HasOne("HobbyXP.Models.PersonalGrowth.Book", "Book")
                        .WithMany("ReadingLogs")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("HobbyXP.Models.PersonalGrowth.CourseSessionLog", b =>
                {
                    b.HasOne("HobbyXP.Models.PersonalGrowth.Course", "Course")
                        .WithMany("SessionLogs")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("HobbyXP.Models.Physical.GymWorkoutEntry", b =>
                {
                    b.HasOne("HobbyXP.Models.Physical.Exercise", "Exercise")
                        .WithMany("WorkoutEntries")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HobbyXP.Models.Physical.GymWorkout", "GymWorkout")
                        .WithMany("Entries")
                        .HasForeignKey("GymWorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("GymWorkout");
                });

            modelBuilder.Entity("HobbyXP.Models.Physical.RunningSession", b =>
                {
                    b.HasOne("HobbyXP.Models.Physical.OfficialRace", "Carrera")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("HobbyXP.Models.Achievements.MedalDefinition", b =>
                {
                    b.Navigation("EarnedInstances");
                });

            modelBuilder.Entity("HobbyXP.Models.Core.PlayerProfile", b =>
                {
                    b.Navigation("HobbyProgresses");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("HobbyXP.Models.Entertainment.MediaSeries", b =>
                {
                    b.Navigation("ChapterLogs");
                });

            modelBuilder.Entity("HobbyXP.Models.Entertainment.VideoGame", b =>
                {
                    b.Navigation("ProgressLogs");
                });

            modelBuilder.Entity("HobbyXP.Models.PersonalGrowth.Book", b =>
                {
                    b.Navigation("ReadingLogs");
                });

            modelBuilder.Entity("HobbyXP.Models.PersonalGrowth.Course", b =>
                {
                    b.Navigation("SessionLogs");
                });

            modelBuilder.Entity("HobbyXP.Models.Physical.Exercise", b =>
                {
                    b.Navigation("WorkoutEntries");
                });

            modelBuilder.Entity("HobbyXP.Models.Physical.GymWorkout", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("HobbyXP.Models.Physical.OfficialRace", b =>
                {
                    b.Navigation("TrainingSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
