<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>HobbyXP.Web</RootNamespace>
    <Version>1.9.0</Version>
    <AssemblyVersion>1.9.0.0</AssemblyVersion>
    <FileVersion>1.9.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HobbyXP.Core\HobbyXP.Core.csproj" />
  </ItemGroup>

</Project>
