// <auto-generated />
using System;
using HobbyXP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HobbyXP.Data.Migrations
{
    [DbContext(typeof(HobbyXpDbContext))]
    partial class HobbyXpDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("HobbyXP.Models.Achievements.AchievementRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FlatBonusPoints")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PointsPerUnit")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitLabel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActionType")
                        .IsUnique();

                    b.ToTable("AchievementRules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionType = "RunningKilometer",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Running por kilómetro",
                            IsActive = true,
                            PointsPerUnit = 10m,
                            UnitLabel = "km"
                        },
                        new
                        {
                            Id = 2,
                            ActionType = "GymWorkoutSaved",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Sesión de gimnasio",
                            IsActive = true,
                            PointsPerUnit = 10m,
                            UnitLabel = "sesión"
                        },
                        new
                        {
                            Id = 3,
                            ActionType = "ProgressiveOverload",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Récord personal (ejercicio)",
                            IsActive = true,
                            PointsPerUnit = 5m,
                            UnitLabel = "ejercicio"
                        },
                        new
                        {
                            Id = 4,
                            ActionType = "OfficialRaceCompleted",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Carrera oficial completada",
                            FlatBonusPoints = 500,
                            IsActive = true,
                            PointsPerUnit = 0m,
                            UnitLabel = "carrera"
                        },
                        new
                        {
                            Id = 5,
                            ActionType = "PuzzleCompleted",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Rompecabezas completado",
                            IsActive = true,
                            PointsPerUnit = 100m,
                            UnitLabel = "rompecabezas"
                        },
                        new
                        {
                            Id = 6,
                            ActionType = "MediaCompleted",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Película terminada",
                            IsActive = true,
                            PointsPerUnit = 20m,
                            UnitLabel = "película"
                        },
                        new
                        {
                            Id = 7,
                            ActionType = "VideoGamePercent",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Avance de videojuego",
                            IsActive = true,
                            PointsPerUnit = 10m,
                            UnitLabel = "%"
                        },
                        new
                        {
                            Id = 8,
                            ActionType = "VideoGamePlatinum",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Videojuego platinado",
                            FlatBonusPoints = 1000,
                            IsActive = true,
                            PointsPerUnit = 0m,
                            UnitLabel = "juego"
                        },
                        new
                        {
                            Id = 9,
                            ActionType = "BookPageRead",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Página leída",
                            IsActive = true,
                            PointsPerUnit = 1m,
                            UnitLabel = "página"
                        },
                        new
                        {
                            Id = 10,
                            ActionType = "BookCompleted",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Libro terminado",
                            FlatBonusPoints = 200,
                            IsActive = true,
                            PointsPerUnit = 0m,
                            UnitLabel = "libro"
                        },
                        new
                        {
                            Id = 11,
                            ActionType = "CourseCompleted",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Curso terminado",
                            FlatBonusPoints = 100,
                            IsActive = true,
                            PointsPerUnit = 0m,
                            UnitLabel = "curso"
                        },
                        new
                        {
                            Id = 12,
                            ActionType = "CourseSessionCompleted",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Sesión de curso",
                            IsActive = true,
                            PointsPerUnit = 10m,
                            UnitLabel = "sesión"
                        },
                        new
                        {
                            Id = 13,
                            ActionType = "MediaChapterWatched",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Serie (XP total repartido en capítulos)",
                            IsActive = true,
                            PointsPerUnit = 100m,
                            UnitLabel = "serie"
                        },
                        new
                        {
                            Id = 14,
                            ActionType = "DietMealOnPlan",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Comida en plan",
                            IsActive = true,
                            PointsPerUnit = 2m,
                            UnitLabel = "comida"
                        },
                        new
                        {
                            Id = 15,
                            ActionType = "DietPerfectDay",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Día perfecto de dieta",
                            FlatBonusPoints = 2,
                            IsActive = true,
                            PointsPerUnit = 0m,
                            UnitLabel = "día"
                        });
                });

            modelBuilder.Entity("HobbyXP.Models.Achievements.EarnedMedal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MedalDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceEntityType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MedalDefinitionId", "EarnedAt");

                    b.ToTable("EarnedMedals", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Achievements.MedalDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("IconPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnlockHint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("XpThreshold")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("SourceType", "XpThreshold")
                        .IsUnique();

                    b.ToTable("MedalDefinitions", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Achievements.Reward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CostInPoints")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("PurchaseUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RedeemedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RedeemedCostInPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceType");

                    b.HasIndex("Status");

                    b.ToTable("Rewards", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Core.DailyQuotaEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActualPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DayUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("GlobalXpRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HobbyLevelAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HobbyLevelBefore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HobbyXpRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PenalizedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequiredPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RestoredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceType", "DayUtc")
                        .IsUnique();

                    b.ToTable("DailyQuotaEvaluations", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Core.HobbyProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<int>("PlayerProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("SpendableXp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalXp")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerProfileId", "SourceType")
                        .IsUnique();

                    b.ToTable("HobbyProgresses", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Core.Milestone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAt");

                    b.ToTable("Milestones", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Core.ModuleDisciplinePause", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PausedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceType")
                        .IsUnique();

                    b.ToTable("ModuleDisciplinePauses", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Core.PlayerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("BaseXpPerLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1000);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("DailyQuotaTrackingStartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DisciplineImmunityUntilUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Aventurero");

                    b.Property<int?>("EquippedRewardId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HobbySpendableLedgerInitialized")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("HonorTitle")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("LastSeenEarnedMedalCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<bool>("SpendableLedgerInitialized")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("SpendableProgressBaselineApplied")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("SpendableXp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalXp")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WeeklyQuotaTrackingStartedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PlayerProfiles", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Core.WeeklyQuotaEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActualPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActualSecondary")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GlobalXpRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HobbyLevelAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HobbyLevelBefore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HobbyXpRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PenalizedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequiredPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequiredSecondary")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RestoredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WeekStartUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceType", "WeekStartUtc")
                        .IsUnique();

                    b.ToTable("WeeklyQuotaEvaluations", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Core.XpTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGlobal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("PlayerProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceEntityType")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EarnedAt");

                    b.HasIndex("PlayerProfileId");

                    b.HasIndex("SourceType");

                    b.ToTable("XpTransactions", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Entertainment.MediaEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("XpEarned")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAt");

                    b.ToTable("MediaEntries", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Entertainment.MediaSeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChaptersWatched")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CompletedMediaEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalChapters")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("XpEarned")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("MediaSeries", null, t =>
                        {
                            t.HasCheckConstraint("CK_MediaSeries_ChaptersWatched", "[ChaptersWatched] >= 0 AND [ChaptersWatched] <= [TotalChapters]");
                        });
                });

            modelBuilder.Entity("HobbyXP.Models.Entertainment.MediaSeriesChapterLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChaptersDone")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WatchDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaSeriesId", "WatchDate");

                    b.ToTable("MediaSeriesChapterLogs", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Entertainment.Puzzle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PieceCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("XpEarned")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Puzzles", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Entertainment.VideoGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletionPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlatinumBonusXp")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PlatinumUnlockedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("XpEarned")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompletionPercentage");

                    b.HasIndex("Status");

                    b.ToTable("VideoGames", null, t =>
                        {
                            t.HasCheckConstraint("CK_VideoGames_CompletionPercentage", "[CompletionPercentage] >= 0 AND [CompletionPercentage] <= 100");
                        });
                });

            modelBuilder.Entity("HobbyXP.Models.Entertainment.VideoGameProgressLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PercentDelta")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ProgressDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("VideoGameId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VideoGameId", "ProgressDate");

                    b.ToTable("VideoGameProgressLogs", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Feedback.Suggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Kind");

                    b.HasIndex("ReportedAt");

                    b.HasIndex("Status");

                    b.ToTable("Suggestions", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.PersonalGrowth.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("PagesRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalPages")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("XpEarned")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("Books", null, t =>
                        {
                            t.HasCheckConstraint("CK_Books_PagesRead", "[PagesRead] >= 0 AND [PagesRead] <= [TotalPages]");
                        });
                });

            modelBuilder.Entity("HobbyXP.Models.PersonalGrowth.BookReadingLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PagesDone")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReadDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookId", "ReadDate");

                    b.ToTable("BookReadingLogs", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.PersonalGrowth.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalSessions")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("XpEarned")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("Courses", null, t =>
                        {
                            t.HasCheckConstraint("CK_Courses_SessionsCompleted", "[SessionsCompleted] >= 0 AND [SessionsCompleted] <= [TotalSessions]");
                        });
                });

            modelBuilder.Entity("HobbyXP.Models.PersonalGrowth.CourseSessionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionsDone")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "SessionDate");

                    b.ToTable("CourseSessionLogs", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Physical.DietDayLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BreakfastStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DayDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DinnerStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("LunchStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("OnPlanCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SnackStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("XpEarned")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DayDate")
                        .IsUnique();

                    b.ToTable("DietDayLogs", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Physical.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("MuscleGroup")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MuscleGroup");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Exercises", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Physical.GymWorkout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TriggeredProgressiveOverload")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WorkoutDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("XpEarned")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutDate");

                    b.ToTable("GymWorkouts", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Physical.GymWorkoutEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("GymWorkoutId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPersonalRecord")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Repetitions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sets")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(8, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GymWorkoutId");

                    b.HasIndex("ExerciseId", "CreatedAt");

                    b.ToTable("GymWorkoutEntries", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Physical.OfficialRace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BonusXpAwarded")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DistanceKm")
                        .HasPrecision(8, 3)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsCompleted");

                    b.ToTable("OfficialRaces", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Physical.RunningSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CarreraId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DistanceKm")
                        .HasPrecision(8, 3)
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double>("PaceMinPerKm")
                        .HasPrecision(8, 3)
                        .HasColumnType("REAL");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("XpEarned")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.HasIndex("RecordedAt");

                    b.HasIndex("SessionType");

                    b.ToTable("RunningSessions", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Physical.RunningSessionSeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DistanceKm")
                        .HasPrecision(8, 3)
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<int>("RunningSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunningSessionId", "SortOrder");

                    b.ToTable("RunningSessionSeries", (string)null);
                });

            modelBuilder.Entity("HobbyXP.Models.Achievements.EarnedMedal", b =>
                {
                    b.HasOne("HobbyXP.Models.Achievements.MedalDefinition", "MedalDefinition")
                        .WithMany("EarnedInstances")
                        .HasForeignKey("MedalDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MedalDefinition");
                });

            modelBuilder.Entity("HobbyXP.Models.Core.HobbyProgress", b =>
                {
                    b.HasOne("HobbyXP.Models.Core.PlayerProfile", "PlayerProfile")
                        .WithMany("HobbyProgresses")
                        .HasForeignKey("PlayerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerProfile");
                });

            modelBuilder.Entity("HobbyXP.Models.Core.XpTransaction", b =>
                {
                    b.HasOne("HobbyXP.Models.Core.PlayerProfile", "PlayerProfile")
                        .WithMany("Transactions")
                        .HasForeignKey("PlayerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerProfile");
                });

            modelBuilder.Entity("HobbyXP.Models.Entertainment.MediaSeriesChapterLog", b =>
                {
                    b.HasOne("HobbyXP.Models.Entertainment.MediaSeries", "MediaSeries")
                        .WithMany("ChapterLogs")
                        .HasForeignKey("MediaSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaSeries");
                });

            modelBuilder.Entity("HobbyXP.Models.Entertainment.VideoGameProgressLog", b =>
                {
                    b.HasOne("HobbyXP.Models.Entertainment.VideoGame", "VideoGame")
                        .WithMany("ProgressLogs")
                        .HasForeignKey("VideoGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VideoGame");
                });

            modelBuilder.Entity("HobbyXP.Models.PersonalGrowth.BookReadingLog", b =>
                {
                    b.HasOne("HobbyXP.Models.PersonalGrowth.Book", "Book")
                        .WithMany("ReadingLogs")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("HobbyXP.Models.PersonalGrowth.CourseSessionLog", b =>
                {
                    b.HasOne("HobbyXP.Models.PersonalGrowth.Course", "Course")
                        .WithMany("SessionLogs")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("HobbyXP.Models.Physical.GymWorkoutEntry", b =>
                {
                    b.HasOne("HobbyXP.Models.Physical.Exercise", "Exercise")
                        .WithMany("WorkoutEntries")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HobbyXP.Models.Physical.GymWorkout", "GymWorkout")
                        .WithMany("Entries")
                        .HasForeignKey("GymWorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("GymWorkout");
                });

            modelBuilder.Entity("HobbyXP.Models.Physical.RunningSession", b =>
                {
                    b.HasOne("HobbyXP.Models.Physical.OfficialRace", "Carrera")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("HobbyXP.Models.Physical.RunningSessionSeries", b =>
                {
                    b.HasOne("HobbyXP.Models.Physical.RunningSession", "RunningSession")
                        .WithMany("Series")
                        .HasForeignKey("RunningSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RunningSession");
                });

            modelBuilder.Entity("HobbyXP.Models.Achievements.MedalDefinition", b =>
                {
                    b.Navigation("EarnedInstances");
                });

            modelBuilder.Entity("HobbyXP.Models.Core.PlayerProfile", b =>
                {
                    b.Navigation("HobbyProgresses");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("HobbyXP.Models.Entertainment.MediaSeries", b =>
                {
                    b.Navigation("ChapterLogs");
                });

            modelBuilder.Entity("HobbyXP.Models.Entertainment.VideoGame", b =>
                {
                    b.Navigation("ProgressLogs");
                });

            modelBuilder.Entity("HobbyXP.Models.PersonalGrowth.Book", b =>
                {
                    b.Navigation("ReadingLogs");
                });

            modelBuilder.Entity("HobbyXP.Models.PersonalGrowth.Course", b =>
                {
                    b.Navigation("SessionLogs");
                });

            modelBuilder.Entity("HobbyXP.Models.Physical.Exercise", b =>
                {
                    b.Navigation("WorkoutEntries");
                });

            modelBuilder.Entity("HobbyXP.Models.Physical.GymWorkout", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("HobbyXP.Models.Physical.OfficialRace", b =>
                {
                    b.Navigation("TrainingSessions");
                });

            modelBuilder.Entity("HobbyXP.Models.Physical.RunningSession", b =>
                {
                    b.Navigation("Series");
                });
#pragma warning restore 612, 618
        }
    }
}
